// src/components/ReportView.jsx
// Doctor-ready Structured Health Report generated upon call completion
// Complies with Tech Assessment NER specification

import { useState } from 'react';

/**
 * @param {Object} props
 * @param {Object} props.report - Generated report JSON
 * @param {Array} props.messages - Verbatim conversation transcript
 * @param {number} props.duration - Call duration in seconds
 * @param {boolean} props.isLoading - Whether report is still generating
 * @param {Function} props.onRestartCall - Callback to restart/continue conversation
 * @param {Function} props.onNextCall - Callback to start a fresh call
 */
export default function ReportView({
  report,
  messages = [],
  duration = 0,
  isLoading = false,
  onRestartCall,
  onNextCall,
}) {
  const [showTranscript, setShowTranscript] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  const formatDuration = (secs) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}m ${s}s`;
  };

  const handleCopyReport = () => {
    if (!report) return;
    const textSummary = `
========================================
MEDIVOICE AI - CLINICAL INTAKE REPORT
========================================
Date: ${new Date().toLocaleString()}
Patient: ${report.patientName || 'Not provided'}
Call Duration: ${formatDuration(duration)}
Intake Quality: ${report.callQuality ? report.callQuality.toUpperCase() : 'PARTIAL'}
Language: ${report.language === 'hi' ? 'Hindi' : 'English'}

[CHIEF COMPLAINT]
${report.chiefComplaint || 'No chief complaint recorded'}

[SYMPTOM PROFILE]
- Onset: ${report.symptomHistory?.onset || 'Not collected'}
- Progression: ${report.symptomHistory?.progression || 'Not collected'}
- Associated Symptoms: ${report.symptomHistory?.associatedSymptoms || 'None reported'}
- Duration: ${report.duration || 'Not collected'}

[SEVERITY & TREND]
- Pain Level: ${report.severity?.painLevel !== null && report.severity?.painLevel !== undefined ? `${report.severity.painLevel}/10` : 'Not rated'}
- Trend: ${report.severity?.trend || 'Unknown'}

[MEDICAL HISTORY & MEDICATIONS]
${report.medicalHistory || 'None reported'}

[AI CLINICAL FLAGS & TRIAGE]
${report.aiFlags && report.aiFlags.length > 0 ? report.aiFlags.map((f) => `• ${f}`).join('\n') : '• No urgent flags identified'}

[RECOMMENDED ACTION]
${report.recommendedAction || 'Follow up with primary care physician.'}

========================================
Generated by MediVoice Clinical Intelligence
========================================
`.trim();

    navigator.clipboard.writeText(textSummary).then(() => {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2500);
    });
  };

  const handleDownloadReport = () => {
    if (!report) return;
    const jsonStr = JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        durationSeconds: duration,
        report,
        transcript: messages,
      },
      null,
      2
    );
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `clinical-report-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Loading state while AI synthesizes report
  if (isLoading || !report) {
    return (
      <div className="report-loading-container" style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '70vh',
        padding: '40px 20px',
        textAlign: 'center',
        animation: 'fade-in-up 0.3s ease'
      }}>
        <div style={{
          width: 72,
          height: 72,
          borderRadius: '50%',
          background: 'var(--color-primary-container)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          boxShadow: '0 8px 28px rgba(0,82,204,0.3)',
          marginBottom: 24,
          animation: 'pulse 1.8s infinite ease-in-out'
        }}>
          <span className="material-symbols-outlined spin" style={{ fontSize: 36, color: '#ffffff' }}>
            clinical_notes
          </span>
        </div>

        <h2 style={{ fontSize: 24, fontWeight: 700, color: 'var(--color-on-surface)', marginBottom: 8 }}>
          Synthesizing Clinical Report...
        </h2>
        <p style={{ fontSize: 14, color: 'var(--color-on-surface-variant)', maxWidth: 440, lineHeight: 1.6 }}>
          MediVoice AI is analyzing the conversation history, extracting chief complaints, symptom progression, and triage flags.
        </p>

        <div style={{
          display: 'flex',
          gap: 8,
          alignItems: 'center',
          marginTop: 24,
          padding: '8px 16px',
          background: 'var(--color-surface-container)',
          borderRadius: 20,
          fontSize: 13,
          color: 'var(--color-primary)'
        }}>
          <span className="material-symbols-outlined spin" style={{ fontSize: 16 }}>sync</span>
          <span>Structuring medical intake data...</span>
        </div>
      </div>
    );
  }

  const pain = report.severity?.painLevel;
  const isHighPain = typeof pain === 'number' && pain >= 7;
  const isMediumPain = typeof pain === 'number' && pain >= 4 && pain < 7;
  const quality = (report.callQuality || 'complete').toLowerCase();

  return (
    <div className="report-container" style={{
      maxWidth: 960,
      width: '100%',
      margin: '0 auto',
      padding: '28px 24px 60px',
      animation: 'fade-in-up 0.3s ease'
    }}>
      {/* Top Banner / Navigation Bar */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 24,
        paddingBottom: 20,
        borderBottom: '1px solid var(--color-outline-variant)'
      }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
            <span className="material-symbols-outlined" style={{ fontSize: 26, color: 'var(--color-primary)' }}>
              medical_information
            </span>
            <h1 style={{ fontSize: 24, fontWeight: 700, color: 'var(--color-on-surface)', margin: 0 }}>
              Clinical Health Screening Report
            </h1>
          </div>
          <p style={{ fontSize: 13, color: 'var(--color-on-surface-variant)', margin: 0 }}>
            Automated Voice Intake Summary • Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>

        {/* Action Buttons Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
          <button
            onClick={handleCopyReport}
            className="btn-outline"
            style={{
              padding: '8px 16px',
              fontSize: 13,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              borderRadius: 'var(--radius)',
              cursor: 'pointer'
            }}
          >
            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>
              {copySuccess ? 'check' : 'content_copy'}
            </span>
            {copySuccess ? 'Copied!' : 'Copy Summary'}
          </button>

          <button
            onClick={handleDownloadReport}
            className="btn-outline"
            style={{
              padding: '8px 16px',
              fontSize: 13,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              borderRadius: 'var(--radius)',
              cursor: 'pointer'
            }}
          >
            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>download</span>
            Export JSON
          </button>

          <button
            onClick={() => window.print()}
            className="btn-outline"
            style={{
              padding: '8px 16px',
              fontSize: 13,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              borderRadius: 'var(--radius)',
              cursor: 'pointer'
            }}
          >
            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>print</span>
            Print
          </button>
        </div>
      </div>

      {/* Overview Metadata Strip */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: 14,
        marginBottom: 24
      }}>
        {/* Patient Name */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius)',
          padding: '14px 18px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-on-surface-variant)', textTransform: 'uppercase' }}>
            Patient Name
          </div>
          <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--color-on-surface)', marginTop: 4 }}>
            {report.patientName && report.patientName !== 'Not provided' ? report.patientName : 'Anonymous / Not Provided'}
          </div>
        </div>

        {/* Call Quality Status */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius)',
          padding: '14px 18px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-on-surface-variant)', textTransform: 'uppercase' }}>
            Intake Status
          </div>
          <div style={{ marginTop: 4, display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 4,
              padding: '2px 10px',
              borderRadius: 12,
              fontSize: 12,
              fontWeight: 600,
              background: quality === 'complete' ? '#e6f7ed' : quality === 'partial' ? '#fff4e5' : '#fce8e6',
              color: quality === 'complete' ? '#0d7a42' : quality === 'partial' ? '#b25e00' : '#c5221f'
            }}>
              <span className="material-symbols-outlined" style={{ fontSize: 14 }}>
                {quality === 'complete' ? 'check_circle' : 'info'}
              </span>
              {quality === 'complete' ? 'Complete Intake' : quality === 'partial' ? 'Partial Screening' : 'Brief / Incomplete'}
            </span>
          </div>
        </div>

        {/* Duration & Turns */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius)',
          padding: '14px 18px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-on-surface-variant)', textTransform: 'uppercase' }}>
            Call Duration & Exchanges
          </div>
          <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-on-surface)', marginTop: 4 }}>
            {formatDuration(duration)} • {messages.filter((m) => m.role === 'user').length} turns
          </div>
        </div>

        {/* Language */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius)',
          padding: '14px 18px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-on-surface-variant)', textTransform: 'uppercase' }}>
            Language Used
          </div>
          <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-on-surface)', marginTop: 4, display: 'flex', alignItems: 'center', gap: 6 }}>
            <span>🌐</span>
            {report.language === 'hi' ? 'Hindi (हिन्दी)' : 'English'}
          </div>
        </div>
      </div>

      {/* Main Chief Complaint Banner Card */}
      <div style={{
        background: 'linear-gradient(135deg, rgba(0,82,204,0.08) 0%, rgba(218,226,255,0.3) 100%)',
        border: '1.5px solid var(--color-primary-container)',
        borderRadius: 'var(--radius-md)',
        padding: '20px 24px',
        marginBottom: 24,
        boxShadow: 'var(--shadow-md)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
          <span className="material-symbols-outlined" style={{ color: 'var(--color-primary)', fontSize: 20 }}>
            stethoscope
          </span>
          <span style={{ fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--color-primary)' }}>
            Chief Complaint & Main Concern
          </span>
        </div>
        <p style={{
          fontSize: 17,
          fontWeight: 600,
          color: 'var(--color-on-surface)',
          lineHeight: 1.5,
          margin: 0
        }}>
          {report.chiefComplaint || 'No chief complaint identified.'}
        </p>
      </div>

      {/* Clinical Grid Sections */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 20, marginBottom: 24 }}>
        
        {/* Section 1: Symptom History & Progression */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius-md)',
          padding: '20px 22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
            <span className="material-symbols-outlined" style={{ fontSize: 20, color: 'var(--color-primary)' }}>
              history
            </span>
            <h3 style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-on-surface)', margin: 0 }}>
              Symptom Profile & History
            </h3>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Onset / Timing</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500 }}>
                {report.symptomHistory?.onset || 'Not collected'}
              </div>
            </div>

            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Progression Over Time</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500 }}>
                {report.symptomHistory?.progression || 'Not collected'}
              </div>
            </div>

            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Associated Symptoms</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500 }}>
                {report.symptomHistory?.associatedSymptoms || 'None reported'}
              </div>
            </div>

            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Total Duration</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500 }}>
                {report.duration || 'Not collected'}
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Severity, Trend & Medical History */}
        <div style={{
          background: 'var(--color-surface)',
          border: '1px solid var(--color-outline-variant)',
          borderRadius: 'var(--radius-md)',
          padding: '20px 22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
            <span className="material-symbols-outlined" style={{ fontSize: 20, color: 'var(--color-primary)' }}>
              speed
            </span>
            <h3 style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-on-surface)', margin: 0 }}>
              Severity, Trend & History
            </h3>
          </div>

          {/* Pain Gauge / Bar */}
          <div style={{ marginBottom: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Reported Severity</span>
              <span style={{
                fontSize: 13,
                fontWeight: 700,
                color: isHighPain ? 'var(--color-error)' : isMediumPain ? '#b25e00' : 'var(--color-primary)'
              }}>
                {typeof pain === 'number' ? `${pain} / 10` : 'Not Rated'}
              </span>
            </div>

            {typeof pain === 'number' ? (
              <div style={{
                height: 8,
                background: 'var(--color-surface-container-high)',
                borderRadius: 4,
                overflow: 'hidden'
              }}>
                <div style={{
                  height: '100%',
                  width: `${Math.min(100, Math.max(5, pain * 10))}%`,
                  background: isHighPain
                    ? 'var(--color-error)'
                    : isMediumPain
                    ? 'linear-gradient(90deg, #f59e0b, #d97706)'
                    : 'var(--color-primary-container)',
                  borderRadius: 4,
                  transition: 'width 0.5s ease'
                }} />
              </div>
            ) : (
              <div style={{ fontSize: 13, color: 'var(--color-on-surface-variant)', fontStyle: 'italic' }}>
                Severity rating not specified by patient.
              </div>
            )}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Symptom Trend</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500, display: 'flex', alignItems: 'center', gap: 6 }}>
                <span className="material-symbols-outlined" style={{
                  fontSize: 16,
                  color: report.severity?.trend === 'worsening' ? 'var(--color-error)' : report.severity?.trend === 'improving' ? '#0d7a42' : 'var(--color-primary)'
                }}>
                  {report.severity?.trend === 'worsening' ? 'trending_up' : report.severity?.trend === 'improving' ? 'trending_down' : 'trending_flat'}
                </span>
                <span style={{ textTransform: 'capitalize' }}>{report.severity?.trend || 'Unknown'}</span>
              </div>
            </div>

            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-on-surface-variant)' }}>Medical History & Medications</div>
              <div style={{ fontSize: 14, color: 'var(--color-on-surface)', marginTop: 2, fontWeight: 500 }}>
                {report.medicalHistory || 'None reported'}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AI Clinical Flags & Triage Alerts */}
      <div style={{
        background: 'var(--color-surface)',
        border: '1px solid var(--color-outline-variant)',
        borderRadius: 'var(--radius-md)',
        padding: '20px 22px',
        marginBottom: 24,
        boxShadow: 'var(--shadow-sm)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 20, color: '#d97706' }}>
            flag
          </span>
          <h3 style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-on-surface)', margin: 0 }}>
            AI Clinical Flags & Key Takeaways
          </h3>
        </div>

        {report.aiFlags && report.aiFlags.length > 0 ? (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
            {report.aiFlags.map((flag, idx) => (
              <div
                key={idx}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 6,
                  background: '#fff9eb',
                  border: '1px solid #fde68a',
                  color: '#92400e',
                  padding: '6px 14px',
                  borderRadius: 8,
                  fontSize: 13.5,
                  fontWeight: 500
                }}
              >
                <span className="material-symbols-outlined" style={{ fontSize: 16, color: '#d97706' }}>priority_high</span>
                {flag}
              </div>
            ))}
          </div>
        ) : (
          <div style={{ fontSize: 13.5, color: 'var(--color-on-surface-variant)', fontStyle: 'italic' }}>
            No red flags or urgent anomalies detected during screening.
          </div>
        )}
      </div>

      {/* Recommended Next Steps / Doctor Advice */}
      <div style={{
        background: 'var(--color-surface-container-low)',
        border: '1px solid var(--color-outline-variant)',
        borderRadius: 'var(--radius-md)',
        padding: '20px 22px',
        marginBottom: 32
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 20, color: 'var(--color-primary)' }}>
            recommend
          </span>
          <h3 style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-primary)', margin: 0 }}>
            Recommended Next Steps
          </h3>
        </div>
        <p style={{ fontSize: 14.5, lineHeight: 1.6, color: 'var(--color-on-surface)', margin: 0 }}>
          {report.recommendedAction || 'Please schedule an in-person or telehealth appointment with a licensed healthcare physician for diagnostic evaluation.'}
        </p>
      </div>

      {/* Collapsible Verbatim Transcript */}
      <div style={{
        background: 'var(--color-surface)',
        border: '1px solid var(--color-outline-variant)',
        borderRadius: 'var(--radius-md)',
        marginBottom: 36,
        overflow: 'hidden'
      }}>
        <button
          onClick={() => setShowTranscript(!showTranscript)}
          style={{
            width: '100%',
            padding: '14px 20px',
            background: 'transparent',
            border: 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer',
            textAlign: 'left'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span className="material-symbols-outlined" style={{ fontSize: 20, color: 'var(--color-primary)' }}>
              format_quote
            </span>
            <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-on-surface)' }}>
              Verbatim Call Transcript ({messages.length} messages)
            </span>
          </div>
          <span className="material-symbols-outlined" style={{
            fontSize: 20,
            color: 'var(--color-on-surface-variant)',
            transform: showTranscript ? 'rotate(180deg)' : 'rotate(0deg)',
            transition: 'transform 0.2s ease'
          }}>
            expand_more
          </span>
        </button>

        {showTranscript && (
          <div style={{
            padding: '16px 20px',
            borderTop: '1px solid var(--color-outline-variant)',
            background: 'var(--color-surface-container-lowest)',
            maxHeight: 360,
            overflowY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: 12
          }}>
            {messages.length === 0 ? (
              <div style={{ fontSize: 13, color: 'var(--color-on-surface-variant)' }}>No messages recorded.</div>
            ) : (
              messages.map((m, idx) => (
                <div key={idx} style={{
                  padding: '10px 14px',
                  borderRadius: 8,
                  background: m.role === 'ai' ? 'var(--color-surface-container-low)' : 'var(--color-primary-fixed)',
                  fontSize: 13.5,
                  lineHeight: 1.5
                }}>
                  <div style={{ fontSize: 11, fontWeight: 700, marginBottom: 2, color: m.role === 'ai' ? 'var(--color-primary)' : 'var(--color-on-primary-fixed-variant)' }}>
                    {m.role === 'ai' ? 'MediVoice AI' : 'Patient'}
                  </div>
                  <div>{m.text}</div>
                </div>
              ))
            )}
          </div>
        )}
      </div>

      {/* Bottom Sticky Action Footer */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        flexWrap: 'wrap',
        padding: '20px',
        background: 'var(--color-surface)',
        border: '1.5px solid var(--color-outline-variant)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-md)'
      }}>
        {/* Restart Call - Continue Conversation */}
        <button
          id="restart-call-btn"
          onClick={onRestartCall}
          className="btn-primary"
          style={{
            padding: '14px 28px',
            borderRadius: 'var(--radius)',
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            fontSize: 15,
            fontWeight: 600,
            background: 'var(--color-primary)',
            color: '#ffffff',
            border: 'none',
            cursor: 'pointer',
            boxShadow: '0 4px 14px rgba(0,82,204,0.3)'
          }}
        >
          <span className="material-symbols-outlined" style={{ fontSize: 20 }}>replay</span>
          Restart Call (Continue Conversation)
        </button>

        {/* Next Patient / New Call */}
        <button
          id="next-call-btn"
          onClick={onNextCall}
          className="btn-outline"
          style={{
            padding: '14px 28px',
            borderRadius: 'var(--radius)',
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            fontSize: 15,
            fontWeight: 600,
            background: 'var(--color-surface)',
            color: 'var(--color-on-surface)',
            border: '1.5px solid var(--color-outline-variant)',
            cursor: 'pointer'
          }}
        >
          <span className="material-symbols-outlined" style={{ fontSize: 20 }}>add_call</span>
          Next Patient / New Call
        </button>
      </div>
    </div>
  );
}
